spring:
  datasource:
    #driver-class-name: org.h2.Driver
    #url: jdbc:h2:mem:test
    #username: san
    #password:
    #type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:test
      username: san
      password: