server:
  port: 80
spring:
  application:
    name: 权限管理系统
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/authoritySystem
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console