server:
  port: 80

spring:
  application:
    name: 权限管理系统
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/authoritySystem;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;MODE=MYSQL
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      data-locations: classpath:db/data.sql
      schema-locations: classpath:db/schema.sql
      mode: always
  thymeleaf:
    cache: false

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
  mapper-locations: mapper/*Mapper.xml

logging:
  level:
    root: warn
    org.springframework.boot.autoconfigure.sql.init: trace
    org.ijunfu.dao: trace

