server:
  port: 80
spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/test
    username: sa
    password:
  sql:
    init:
      schema-locations: classpath:db/schema.sql
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

#  cache:
#    type: redis
#    redis:
#      use-key-prefix: true    # 是否使用key前缀
#      key-prefix: ssm_        # key 前缀，
#      cache-null-values: false  # 是否缓存null值
#      time-to-live: 10s   # 活跃时间
#  redis:
#    host:
#    port:
#    password:

xmemcached:
  servers: localhost:11211
  poolSize: 10
  opTimeout: 3000


mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: info
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace