spring:
  datasource:     # 数据源配置
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 50
  h2:
    console:  # H2database 控制台配置
      enabled: true
      path: /h2-console
      settings:
        trace: true
  jpa:
    show-sql: true    # 显示SQL
    hibernate:
      ddl-auto: update
  main:
    banner-mode: off # 关闭SpringBoot

