server:
  port: 80
spring:
  application:
    name: 电脑商城
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/mall
    username: sa
    password:
    hikari:
      pool-name: Hikari_Mall
      maximum-pool-size: 20
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  redis:
    host: lo
    port: 1
    password:

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

