db:
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:test
  username: root
  password: 123456hikari
  serverTimeout: 3
  dataSize: 5
datasource:
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:test
  username: root
  password: 123456hikari