db:
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:test
  username: root
  password: 123456hikari
datasource:
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:test
  username: root
  password: 123456hikari