spring:
  application:
    name: MyBatis&H2database
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/test
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

