spring:
  task:
    scheduling:
      pool:
        size: 10      # 线程池大小
      thread-name-prefix: sp_task_    # 线程前缀
      shutdown:
        await-termination: false  # 线程池关闭时，等待所有任务完成
        await-termination-period: 10s # 调度线程关闭之前，最大等待时间，确保最后一定关闭


